[package]
name = "clinv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.0", features = ["derive"] }
rusqlite = "0.36.0"
tempfile = "3.20.0"
wkhtmltopdf = "0.4.0"
